/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.configclass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Angie
 */
public class internalpaymentsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form internalpaymentsForm
     */
    public internalpaymentsForm() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        javax.swing.plaf.basic.BasicInternalFrameUI bi = (javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    private void clearForm() {
    p_id.setText("");
    p_mid.setText("");
    p_amount.setText("");
    type.setSelectedIndex(0); // Reset JComboBox
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        type = new javax.swing.JComboBox<>();
        firstname2 = new javax.swing.JLabel();
        firstname4 = new javax.swing.JLabel();
        firstname5 = new javax.swing.JLabel();
        firstname6 = new javax.swing.JLabel();
        p_amount = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        p_mid = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        st_label1 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        st_label2 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        st_label3 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENTS FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrong.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 70, 40));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        type.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Gcash", "Card" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        firstname2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname2.setText("Payment Type:");
        jPanel3.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 30));

        firstname4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname4.setText("Amount:");
        jPanel3.add(firstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 30));

        firstname5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname5.setText("Payments Id:");
        jPanel3.add(firstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        firstname6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname6.setText(" Members Id:");
        jPanel3.add(firstname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));
        jPanel3.add(p_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 30));
        jPanel3.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));
        jPanel3.add(p_mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 30));

        view.setBackground(new java.awt.Color(204, 204, 204));
        view.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMouseExited(evt);
            }
        });
        view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label1.setBackground(new java.awt.Color(255, 255, 255));
        st_label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        st_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label1.setText("View");
        view.add(st_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jPanel3.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 80, 40));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label2.setBackground(new java.awt.Color(255, 255, 255));
        st_label2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        st_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label2.setText("Add");
        add.add(st_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 40));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label3.setBackground(new java.awt.Color(255, 255, 255));
        st_label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        st_label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label3.setText("Update");
        update.add(st_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed

    }//GEN-LAST:event_typeActionPerformed

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
try {
    config.configclass dbc = new config.configclass();

    String sql = "SELECT * FROM payments WHERE r_id = ?";
    Object[] values = { Integer.parseInt(p_id.getText()) };

    // Assign the ResultSet returned by viewData to a variable
    ResultSet rs = dbc.viewData(sql, values);

    // Now rs exists and you can use it
    if (rs.next()) {
        p_mid.setText(rs.getString("m_id"));
        p_amount.setText(rs.getString("p_amount"));
        type.setSelectedItem(rs.getString("p_type"));
    } else {
        JOptionPane.showMessageDialog(this, "Payment not found!");
    }

    rs.close(); // always close ResultSet
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Please enter a valid Payment ID.");
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_viewMouseClicked

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseEntered

    private void viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        try {
        String sql = "INSERT INTO payments (m_id, p_amount, p_type) VALUES (?, ?, ?)";
        Object[] values = {
            Integer.parseInt(p_mid.getText()),     // m_id
            Double.parseDouble(p_amount.getText()),// p_amount
            type.getSelectedItem().toString()      // p_type
        };

        configclass dbc = new configclass();
        dbc.insertData(sql);
        JOptionPane.showMessageDialog(this, "Payment added successfully!");
        clearForm();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers for Member ID and Amount.");
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
         config.configclass dbc = new config.configclass();

    try {
        String sql = "UPDATE payments SET m_id = ?, p_amount = ?, p_type = ? WHERE r_id = ?";
        Object[] values = {
            Integer.parseInt(p_mid.getText()),       // Member ID
            Double.parseDouble(p_amount.getText()), // Payment Amount
            type.getSelectedItem().toString(),      // Payment Type (Cash/Card)
            Integer.parseInt(p_id.getText())        // Payment ID (r_id)
        };

        dbc.updateData(sql); // your existing method in configclass

        JOptionPane.showMessageDialog(this, "Payment updated successfully!");
        clearForm();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers for Member ID, Amount, and Payment ID.");
    }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname4;
    private javax.swing.JLabel firstname5;
    private javax.swing.JLabel firstname6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel p_amount;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_mid;
    public javax.swing.JLabel st_label1;
    public javax.swing.JLabel st_label2;
    public javax.swing.JLabel st_label3;
    public javax.swing.JComboBox<String> type;
    public javax.swing.JPanel update;
    public javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
