/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_app;

import config.configclass;
import internalPages.exercise_page;
import internalPages.workoutPlan_page;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Angie
 */
public class exerciseForm extends javax.swing.JFrame {
private boolean isRefreshing = false;
    /**
     * Creates new form exerciseForm
     */
    public exerciseForm() {
           if (!config.Singleton.getInstance().isLoggedIn()) {
        JOptionPane.showMessageDialog(null, "Please Login First!");
        new logIn().setVisible(true);
        this.dispose();
        return; 
    }
        initComponents();
        fillPlanCombo();
        
        this.setBackground(new java.awt.Color(0,0,0,0));
                
    }
   private void fillPlanCombo() {
    isRefreshing = true; // Block events
    try {
        configclass dbc = new configclass();
        ResultSet rs = dbc.getData("SELECT wp_id FROM workout_plans");
        
        wp_id.removeAllItems(); // This usually triggers ActionPerformed!
        
        while(rs.next()) {
            wp_id.addItem(rs.getString("wp_id"));
        }
    } catch(Exception e) {
        System.out.println("Combo Error: " + e.getMessage());
    } finally {
        isRefreshing = false; // Allow events again
    }
    
    // Manually trigger the first load now that the block is off
    if (wp_id.getItemCount() > 0) {
        wp_id.setSelectedIndex(0);
        // Manually call it once to fill the text field
        wp_idActionPerformed(null); 
    }
}
   private int validateForm() {
    // Check if Exercise Name and Rest Time are filled
    if (ex_name.getText().trim().isEmpty() || rest.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Exercise Name and Rest Time!");
        return 0;
    }
    return 1;
}
   public String action;
      public void close(){
        this.dispose();
        dashboard dash = new dashboard();
        dash.setVisible(true);
        exercise_page up = new exercise_page();
        dash.maindesktop.add(up).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        body = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 10;
                int borderRadius = 25;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        body.setOpaque(false);
        firstname2 = new javax.swing.JLabel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);
        ;
        st_label = new javax.swing.JLabel();
        firstname6 = new javax.swing.JLabel();
        ex_name = new javax.swing.JTextField();
        firstname7 = new javax.swing.JLabel();
        firstname3 = new javax.swing.JLabel();
        firstname4 = new javax.swing.JLabel();
        rest = new javax.swing.JTextField();
        wp_id = new javax.swing.JComboBox<>();
        header = header = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 10;
                int borderRadius = 25;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow (Top corners only)
                for (int i = 0; i < shadowSize; i++) {
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    // Draw shadow as a round rect
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel
                g2.setColor(getBackground());

                // --- THE TRICK FOR TOP BORDER RADIUS ONLY ---
                // Fill the top half with rounded corners
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                // Fill the bottom half with a sharp rectangle to "cancel out" the bottom curves
                // We start from the middle and fill to the very bottom
                g2.fillRect(shadowSize, shadowSize + (height / 2), width, (height / 2));

                g2.dispose();
            }
        };
        header.setOpaque(false);
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        ex_id = new javax.swing.JLabel();
        Sets = new javax.swing.JSpinner();
        Reps = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        body.setBackground(new java.awt.Color(244, 247, 246));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname2.setForeground(new java.awt.Color(27, 42, 78));
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname2.setText("Rest Time:");
        body.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, 30));

        add.setBackground(new java.awt.Color(243, 156, 18));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 80, 50));

        body.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 280, 50));

        firstname6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname6.setForeground(new java.awt.Color(27, 42, 78));
        firstname6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname6.setText("Workout Id:");
        body.add(firstname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 30));

        ex_name.setEditable(false);
        ex_name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ex_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ex_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        ex_name.setOpaque(false);
        ex_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_nameActionPerformed(evt);
            }
        });
        body.add(ex_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, 30));

        firstname7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname7.setForeground(new java.awt.Color(27, 42, 78));
        firstname7.setText("Exercise Name:");
        body.add(firstname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        firstname3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname3.setForeground(new java.awt.Color(27, 42, 78));
        firstname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname3.setText("Sets:");
        body.add(firstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 50, 30));

        firstname4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname4.setForeground(new java.awt.Color(27, 42, 78));
        firstname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname4.setText("Reps:");
        body.add(firstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 50, 30));

        rest.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rest.setForeground(new java.awt.Color(27, 42, 78));
        rest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });
        body.add(rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, 30));

        wp_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        wp_id.setForeground(new java.awt.Color(27, 42, 78));
        wp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wp_idActionPerformed(evt);
            }
        });
        body.add(wp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 30));

        header.setBackground(new java.awt.Color(27, 42, 78));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXERCISE FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        header.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        close.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("×");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 50));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));
        body.add(ex_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, 30));

        Sets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sets.setModel(new javax.swing.SpinnerNumberModel(1, 0, 12, 1));
        Sets.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SetsStateChanged(evt);
            }
        });
        body.add(Sets, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 30));

        Reps.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reps.setModel(new javax.swing.SpinnerNumberModel(1, 0, 12, 1));
        Reps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RepsStateChanged(evt);
            }
        });
        body.add(Reps, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
   if (validateForm() == 1) { 
        configclass dbc = new configclass();

        String workoutPlanID = (wp_id.getSelectedItem() != null) ? wp_id.getSelectedItem().toString() : "";
        String exerciseName = ex_name.getText().trim();
        String setsValue = Sets.getValue().toString();
        String repsValue = Reps.getValue().toString();
        String restTime = rest.getText().trim();

        String sql;

        if ("Add".equals(action)) {
            sql = "INSERT INTO exercises (wp_id, exercise_name, sets, reps, rest_time) "
                + "VALUES ('" + workoutPlanID + "', '" + exerciseName + "', '" + setsValue + "', '" + repsValue + "', '" + restTime + "')";

            if (dbc.insertData(sql) == 1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Exercise Added!");
                close(); 
            }
        } else if ("Update".equals(action)) {
            String exerciseID = ex_id.getText(); 
            sql = "UPDATE exercises SET "
                + "wp_id = '" + workoutPlanID + "', "
                + "exercise_name = '" + exerciseName + "', "
                + "sets = '" + setsValue + "', "
                + "reps = '" + repsValue + "', "
                + "rest_time = '" + restTime + "' "
                + "WHERE ex_id = '" + exerciseID + "'";

            dbc.updateData(sql);
            javax.swing.JOptionPane.showMessageDialog(null, "Exercise Updated!");
            close();
        }
        }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void ex_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_nameActionPerformed
    
    }//GEN-LAST:event_ex_nameActionPerformed

    private void wp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wp_idActionPerformed
    if (isRefreshing) return; 

    if (wp_id.getSelectedItem() != null) {
        String selectedID = wp_id.getSelectedItem().toString();
        try {
            config.configclass dbc = new config.configclass();
            String query = "SELECT plan_name FROM workout_plans WHERE wp_id = '" + selectedID + "'";
            java.sql.ResultSet rs = dbc.getData(query);
            
            if (rs.next()) {
                ex_name.setText(rs.getString("plan_name"));
            }
        } catch (Exception e) {
            System.out.println("Fetch Plan Name Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_wp_idActionPerformed

    private void SetsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SetsStateChanged

    }//GEN-LAST:event_SetsStateChanged

    private void RepsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RepsStateChanged

    }//GEN-LAST:event_RepsStateChanged

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit the application?",
            "Exit Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (response == javax.swing.JOptionPane.YES_OPTION) {

            close();
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exerciseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exerciseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exerciseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exerciseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exerciseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSpinner Reps;
    public javax.swing.JSpinner Sets;
    public javax.swing.JPanel add;
    private javax.swing.JPanel body;
    private javax.swing.JLabel close;
    public javax.swing.JLabel ex_id;
    public javax.swing.JTextField ex_name;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname3;
    private javax.swing.JLabel firstname4;
    private javax.swing.JLabel firstname6;
    private javax.swing.JLabel firstname7;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField rest;
    public javax.swing.JLabel st_label;
    public javax.swing.JComboBox<String> wp_id;
    // End of variables declaration//GEN-END:variables
}
