package main_app;


import config.configclass;
import internalPages.manageUser;
import internalPages.member;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class membersForm extends javax.swing.JFrame {

    /**
     * Creates new form memberForm
     */
    public membersForm() {
        initComponents();
            m_dura.setModel(new javax.swing.SpinnerNumberModel(1, 1, 36, 1));
    m_type.addActionListener(e -> updateMembershipDates());
    m_dura.addChangeListener(e -> updateMembershipDates());
    
        updateMembershipDates();
    }
    
      public void close(){
        this.dispose();
        dashboard dash = new dashboard();
        dash.setVisible(true);
        member up = new member();
        dash.maindesktop.add(up).setVisible(true);
    }
int validateRegister() {
    int result;


    if (m_name.getText().trim().isEmpty() || m_cont.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Name and Contact are required!");
        result = 0;
    } 
    else if (m_type.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(null, "Please select a Membership Type!");
        result = 0;
    }
    else if (Integer.parseInt(m_dura.getValue().toString()) <= 0) {
        JOptionPane.showMessageDialog(null, "Duration must be at least 1 month!");
        result = 0;
    } 
    else {
        result = 1; 
    }

    return result;
}

public void updateMembershipDates() {
    try {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        
        m_start.setText(sdf.format(cal.getTime()));
        
        int months = (Integer) m_dura.getValue();
        
        cal.add(Calendar.MONTH, months);
        
        m_expiry.setText(sdf.format(cal.getTime()));
        
    } catch (Exception e) {
   
        System.out.println("Error calculating dates: " + e.getMessage());
    }
}
      public String action;
    
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberform = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        wrong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        update = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        m_cont = new javax.swing.JTextField();
        firstname1 = new javax.swing.JLabel();
        m_type = new javax.swing.JComboBox<>();
        firstname2 = new javax.swing.JLabel();
        m_dura = new javax.swing.JSpinner();
        firstname3 = new javax.swing.JLabel();
        m_id = new javax.swing.JLabel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);

        ;
        st_label = new javax.swing.JLabel();
        firstname5 = new javax.swing.JLabel();
        m_name = new javax.swing.JTextField();
        firstname6 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        firstname7 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        firstname4 = new javax.swing.JLabel();
        firstname8 = new javax.swing.JLabel();
        m_start = new javax.swing.JLabel();
        m_expiry = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        memberform.setBackground(new java.awt.Color(204, 204, 204));
        memberform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        memberform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(27, 42, 78));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEMBERS FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        wrong.setBackground(new java.awt.Color(27, 42, 78));
        wrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrongMouseClicked(evt);
            }
        });
        wrong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("×");
        wrong.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        jPanel4.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 70, 60));

        memberform.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel3.setBackground(new java.awt.Color(244, 247, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(102, 102, 102));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, -1));

        firstname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname.setForeground(new java.awt.Color(27, 42, 78));
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("Contact:");
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 30));

        m_cont.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m_cont.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        m_cont.setOpaque(false);
        m_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_contActionPerformed(evt);
            }
        });
        jPanel3.add(m_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        firstname1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname1.setForeground(new java.awt.Color(27, 42, 78));
        firstname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname1.setText("Id:");
        jPanel3.add(firstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 20, 30));

        m_type.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m_type.setForeground(new java.awt.Color(27, 42, 78));
        m_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Vip", "Student" }));
        m_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_typeActionPerformed(evt);
            }
        });
        jPanel3.add(m_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, -1));

        firstname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname2.setForeground(new java.awt.Color(27, 42, 78));
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname2.setText("Start Date:");
        jPanel3.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 90, 30));

        m_dura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_dura.setModel(new javax.swing.SpinnerNumberModel(1, 0, 12, 1));
        m_dura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m_duraStateChanged(evt);
            }
        });
        jPanel3.add(m_dura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        firstname3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname3.setForeground(new java.awt.Color(27, 42, 78));
        firstname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname3.setText("Duration:");
        jPanel3.add(firstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 30));
        jPanel3.add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 30));

        add.setBackground(new java.awt.Color(243, 156, 18));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 50));

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 50));

        firstname5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname5.setForeground(new java.awt.Color(27, 42, 78));
        firstname5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname5.setText("Full Name:");
        jPanel3.add(firstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        m_name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        m_name.setOpaque(false);
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        jPanel3.add(m_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        firstname6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname6.setForeground(new java.awt.Color(27, 42, 78));
        firstname6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname6.setText("Type:");
        jPanel3.add(firstname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 50, 30));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gender.setForeground(new java.awt.Color(27, 42, 78));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        firstname7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname7.setForeground(new java.awt.Color(27, 42, 78));
        firstname7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname7.setText("Gender:");
        jPanel3.add(firstname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));

        status.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        status.setForeground(new java.awt.Color(27, 42, 78));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        firstname4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname4.setForeground(new java.awt.Color(27, 42, 78));
        firstname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname4.setText("Expiry Date:");
        jPanel3.add(firstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 100, 30));

        firstname8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname8.setForeground(new java.awt.Color(27, 42, 78));
        firstname8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname8.setText("Status:");
        jPanel3.add(firstname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 90, 30));

        m_start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        jPanel3.add(m_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 30));

        m_expiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        jPanel3.add(m_expiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 180, 30));

        memberform.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(memberform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(memberform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(bodycolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void m_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_contActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_m_contActionPerformed

    private void wrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrongMouseClicked
   // 1. Close this popup form
    this.dispose();

    // 2. Find the dashboard window you are already in
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    try {
        // 3. Access the blue area (maindesktop)
        java.lang.reflect.Field field = topFrame.getClass().getDeclaredField("maindesktop");
        field.setAccessible(true);
        javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) field.get(topFrame);
        
        // 4. Clear the screen and load the MEMBERS table
        desktop.removeAll();
        member m = new member(); // This loads your table page
        desktop.add(m).setVisible(true);
        
        // 5. Refresh the screen
        desktop.revalidate();
        desktop.repaint();
        
    } catch (Exception e) {
  
        System.out.println("Error returning to Members: " + e.getMessage());
    }
    }//GEN-LAST:event_wrongMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
   if(validateRegister() != 1) return;

    // 2. Collect Data (Arranged by your Form Layout)
    // Left Side Columns
    String id = m_id.getText();
    String name = m_name.getText().trim();
    String gen = gender.getSelectedItem().toString(); 
    String contact = m_cont.getText().trim();
    String type = m_type.getSelectedItem().toString();
    int months = (Integer) m_dura.getValue();
    
    // Right Side Columns
    String stat = status.getSelectedItem().toString(); 
    
    // 3. Date Parsing (Converting UI Label to Database format)
    SimpleDateFormat displayFormat = new SimpleDateFormat("MMMM dd, yyyy");
    SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    String startStr = "";
    String expiryStr = "";
    
    try {
        startStr = dbFormat.format(displayFormat.parse(m_start.getText()));
        expiryStr = dbFormat.format(displayFormat.parse(m_expiry.getText()));
    } catch (Exception e) {
        // Fallback to current date if labels are unreadable
        startStr = dbFormat.format(new java.util.Date());
        expiryStr = startStr; 
    }

    configclass dbc = new configclass();

    // 4. Database Operations
    if(action.equals("Add")) {
        String sql = "INSERT INTO members (m_fname, m_gender, contact, m_type, m_duration, start_date, expiry_date, status) "
                   + "VALUES ("
                   + "'" + name + "', "
                   + "'" + gen + "', "
                   + "'" + contact + "', "
                   + "'" + type + "', "
                   + "'" + months + "', "
                   + "'" + startStr + "', "
                   + "'" + expiryStr + "', "
                   + "'" + stat + "')";
        
        if(dbc.insertData(sql) == 1){
            JOptionPane.showMessageDialog(null, "Member Successfully Registered!");
            close();
        }

    } else if(action.equals("Update")) {
        String sql = "UPDATE members SET "
                   + "m_fname = '" + name + "', "
                   + "m_gender = '" + gen + "', "
                   + "contact = '" + contact + "', "
                   + "m_type = '" + type + "', "
                   + "m_duration = '" + months + "', "
                   + "start_date = '" + startStr + "', "
                   + "expiry_date = '" + expiryStr + "', "
                   + "status = '" + stat + "' "
                   + "WHERE m_id = '" + id + "'";
        
        dbc.updateData(sql);
        JOptionPane.showMessageDialog(null, "Member Updated Successfully!");
        close();
    }
    }//GEN-LAST:event_addMouseClicked
    
    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
       add.setBackground(new Color(255, 179, 71));   
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
      add.setBackground(new Color(243, 156, 18)) ;  
    }//GEN-LAST:event_addMouseExited

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void m_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_typeActionPerformed
     

    }//GEN-LAST:event_m_typeActionPerformed

    private void m_duraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m_duraStateChanged
    
    }//GEN-LAST:event_m_duraStateChanged

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel firstname1;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname3;
    private javax.swing.JLabel firstname4;
    private javax.swing.JLabel firstname5;
    private javax.swing.JLabel firstname6;
    private javax.swing.JLabel firstname7;
    private javax.swing.JLabel firstname8;
    public javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField m_cont;
    public javax.swing.JSpinner m_dura;
    public javax.swing.JLabel m_expiry;
    public javax.swing.JLabel m_id;
    public javax.swing.JTextField m_name;
    public javax.swing.JLabel m_start;
    public javax.swing.JComboBox<String> m_type;
    private javax.swing.JPanel memberform;
    public javax.swing.JLabel st_label;
    public javax.swing.JComboBox<String> status;
    private javax.swing.JPanel update;
    private javax.swing.JPanel wrong;
    // End of variables declaration//GEN-END:variables
}
