package main_app;


import config.configclass;
import internalPages.manageUser;
import internalPages.member;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class membersForm extends javax.swing.JFrame {

    /**
     * Creates new form memberForm
     */
    public membersForm() {
        initComponents();
            m_dura.setModel(new javax.swing.SpinnerNumberModel(1, 1, 36, 1));
            m_type.addActionListener(e -> setAutomaticPrice());
m_dura.addChangeListener(e -> setAutomaticPrice());
        setAutomaticPrice();
    }
    
      public void close(){
        this.dispose();
        dashboard dash = new dashboard();
        dash.setVisible(true);
        member up = new member();
        dash.maindesktop.add(up).setVisible(true);
    }
int validateRegister() {
    int result;


    if (m_name.getText().trim().isEmpty() || m_cont.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Name and Contact are required!");
        result = 0;
    } 
    else if (m_type.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(null, "Please select a Membership Type!");
        result = 0;
    }
    else if (Integer.parseInt(m_dura.getValue().toString()) <= 0) {
        JOptionPane.showMessageDialog(null, "Duration must be at least 1 month!");
        result = 0;
    } 
    else {
        result = 1; 
    }

    return result;
}

public void setAutomaticPrice() {
    try {
        String type = m_type.getSelectedItem().toString();
        int months = (Integer) m_dura.getValue();
        double price = 0;

        switch(type) {
            case "Monthly": price = 500; break;
            case "Vip": price = 1500; break;
            case "Student": price = 350; break;
        }

        double total = price * months;
        m_amount.setText(String.format("%.2f", total));

    } catch (Exception e) {
        m_amount.setText("0.00");
    }
}
      public String action;
    
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberform = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        wrong = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        update = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        m_cont = new javax.swing.JTextField();
        firstname1 = new javax.swing.JLabel();
        m_type = new javax.swing.JComboBox<>();
        firstname2 = new javax.swing.JLabel();
        m_dura = new javax.swing.JSpinner();
        m_amount = new javax.swing.JTextField();
        firstname3 = new javax.swing.JLabel();
        firstname4 = new javax.swing.JLabel();
        m_id = new javax.swing.JLabel();
        add1 = new javax.swing.JPanel();
        st_label = new javax.swing.JLabel();
        firstname5 = new javax.swing.JLabel();
        m_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        memberform.setBackground(new java.awt.Color(204, 204, 204));
        memberform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        memberform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEMBERS FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        wrong.setBackground(new java.awt.Color(51, 51, 51));
        wrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrongMouseClicked(evt);
            }
        });
        wrong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrong.png"))); // NOI18N
        wrong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 40));

        jPanel4.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 70, 60));

        memberform.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(102, 102, 102));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, -1));

        firstname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("Contact:");
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        m_cont.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_cont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_cont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        m_cont.setOpaque(false);
        m_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_contActionPerformed(evt);
            }
        });
        jPanel3.add(m_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 200, 30));

        firstname1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname1.setText("Id:");
        jPanel3.add(firstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 20, 30));

        m_type.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Vip", "Student" }));
        m_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_typeActionPerformed(evt);
            }
        });
        jPanel3.add(m_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        firstname2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname2.setText("Type:");
        jPanel3.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        m_dura.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_dura.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1759064640000L), null, java.util.Calendar.DAY_OF_MONTH));
        m_dura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m_duraStateChanged(evt);
            }
        });
        jPanel3.add(m_dura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 30));

        m_amount.setEditable(false);
        m_amount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        m_amount.setOpaque(false);
        m_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_amountActionPerformed(evt);
            }
        });
        jPanel3.add(m_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 30));

        firstname3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname3.setText("Duration:");
        jPanel3.add(firstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        firstname4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname4.setText("Amount:");
        jPanel3.add(firstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 30));
        jPanel3.add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, 30));

        add1.setBackground(new java.awt.Color(204, 204, 204));
        add1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add1MouseExited(evt);
            }
        });
        add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add1.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jPanel3.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, 40));

        firstname5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname5.setText("Full Name:");
        jPanel3.add(firstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        m_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        m_name.setOpaque(false);
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        jPanel3.add(m_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 30));

        memberform.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(memberform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(memberform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(bodycolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void m_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_contActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_contActionPerformed

    private void wrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrongMouseClicked
   // 1. Close this popup form
    this.dispose();

    // 2. Find the dashboard window you are already in
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    try {
        // 3. Access the blue area (maindesktop)
        java.lang.reflect.Field field = topFrame.getClass().getDeclaredField("maindesktop");
        field.setAccessible(true);
        javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) field.get(topFrame);
        
        // 4. Clear the screen and load the MEMBERS table
        desktop.removeAll();
        member m = new member(); // This loads your table page
        desktop.add(m).setVisible(true);
        
        // 5. Refresh the screen
        desktop.revalidate();
        desktop.repaint();
        
    } catch (Exception e) {
  
        System.out.println("Error returning to Members: " + e.getMessage());
    }
    }//GEN-LAST:event_wrongMouseClicked

    private void m_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_amountActionPerformed

    }//GEN-LAST:event_m_amountActionPerformed

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
    int check = validateRegister();
    if(check != 1){
        JOptionPane.showMessageDialog(null, "All fields are required!");
        return;
    }

    // Get common values
    String name = m_name.getText().trim();
    String type = m_type.getSelectedItem().toString();
    int months = (Integer) m_dura.getValue();
    double amount = Double.parseDouble(m_amount.getText());
    
    // Calculate start and expiry dates
    Calendar cal = Calendar.getInstance();
    java.util.Date startDate = cal.getTime();
    cal.add(Calendar.MONTH, months);
    java.util.Date expiryDate = cal.getTime();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String startStr = sdf.format(startDate);
    String expiryStr = sdf.format(expiryDate);

    configclass dbc = new configclass();

    if(action.equals("Add")) {
        String sql = "INSERT INTO members ("
                   + "m_fname, m_type, m_amount, m_duration, contact, start_date, expiry_date"
                   + ") VALUES ("
                   + "'" + name + "', "
                   + "'" + type + "', "
                   + "'" + amount + "', "
                   + "'" + months + "', "
                   + "'" + m_cont.getText().trim() + "', "
                   + "'" + startStr + "', "
                   + "'" + expiryStr + "'"
                   + ")";
        int result = dbc.insertData(sql);
        if(result == 1){
            JOptionPane.showMessageDialog(null, "Member Successfully Registered!\nTotal: " + amount);
            close();
        } else {
            System.out.println("Saving Data Failed!");
        }

    } else if(action.equals("Update")) {
        String sql = "UPDATE members SET "
                   + "m_fname = '" + name + "', "
                   + "m_type = '" + type + "', "
                   + "m_amount = '" + amount + "', "
                   + "m_duration = '" + months + "', "
                   + "m_contact = '" + m_cont.getText().trim() + "', "
                   + "start_date = '" + startStr + "', "
                   + "expiry_date = '" + expiryStr + "' "
                   + "WHERE m_id = '" + m_id.getText() + "'";
        dbc.updateData(sql);
        JOptionPane.showMessageDialog(null, "Member Updated Successfully!");
        close();
    }
    }//GEN-LAST:event_add1MouseClicked
    
    private void add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseEntered

    }//GEN-LAST:event_add1MouseEntered

    private void add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseExited

    }//GEN-LAST:event_add1MouseExited

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void m_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_typeActionPerformed
      setAutomaticPrice();

    }//GEN-LAST:event_m_typeActionPerformed

    private void m_duraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m_duraStateChanged
       setAutomaticPrice();

    }//GEN-LAST:event_m_duraStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add1;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel firstname1;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname3;
    private javax.swing.JLabel firstname4;
    private javax.swing.JLabel firstname5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField m_amount;
    public javax.swing.JTextField m_cont;
    public javax.swing.JSpinner m_dura;
    public javax.swing.JLabel m_id;
    public javax.swing.JTextField m_name;
    public javax.swing.JComboBox<String> m_type;
    private javax.swing.JPanel memberform;
    public javax.swing.JLabel st_label;
    private javax.swing.JPanel update;
    private javax.swing.JPanel wrong;
    // End of variables declaration//GEN-END:variables
}
