/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_app;

import config.configclass;
import internalPages.member;
import internalPages.workoutPlan_page;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Angie
 */
public class workoutForm extends javax.swing.JFrame {

    /**
     * Creates new form workoutForm
     */
    public workoutForm() {
           if (!config.Singleton.getInstance().isLoggedIn()) {
        JOptionPane.showMessageDialog(null, "Please Login First!");
        new logIn().setVisible(true);
        this.dispose();
        return; 
    }
        initComponents();
        fillMemberCombo();
    }
    
  private void fillMemberCombo() {
    try {
        configclass dbc = new configclass();
      
    
        ResultSet rs = dbc.getData("SELECT m_id, m_fname FROM members");
        while(rs.next()) {
            m_id.addItem(rs.getString("m_id") + " - " + rs.getString("m_fname"));
        }
    } catch(Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    
    private int validateForm() {
    if (p_name.getSelectedItem().toString().isEmpty() || Trainer.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required!");
        return 0;
    }
    return 1;
}
       public String action; 
       
        public void close(){
        this.dispose();
        dashboard dash = new dashboard();
        dash.setVisible(true);
        workoutPlan_page up = new workoutPlan_page();
        dash.maindesktop.add(up).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        Trainer = new javax.swing.JTextField();
        firstname1 = new javax.swing.JLabel();
        p_name = new javax.swing.JComboBox<>();
        firstname2 = new javax.swing.JLabel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);

        ;
        st_label = new javax.swing.JLabel();
        firstname5 = new javax.swing.JLabel();
        firstname6 = new javax.swing.JLabel();
        week_dura = new javax.swing.JComboBox<>();
        firstname7 = new javax.swing.JLabel();
        Intensity = new javax.swing.JComboBox<>();
        firstname8 = new javax.swing.JLabel();
        m_id = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        planId = new javax.swing.JLabel();
        Goal = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(244, 247, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname.setForeground(new java.awt.Color(27, 42, 78));
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("Trainer:");
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 70, 30));

        Trainer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Trainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(209, 213, 216), java.awt.Color.darkGray, null, null));
        Trainer.setOpaque(false);
        Trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerActionPerformed(evt);
            }
        });
        jPanel3.add(Trainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 30));

        firstname1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname1.setForeground(new java.awt.Color(27, 42, 78));
        firstname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname1.setText("Member Id:");
        jPanel3.add(firstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 30));

        p_name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        p_name.setForeground(new java.awt.Color(27, 42, 78));
        p_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weight Loss", "Muscle Gain", "Cardio Blast", "Strength" }));
        p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nameActionPerformed(evt);
            }
        });
        jPanel3.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, -1));

        firstname2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname2.setForeground(new java.awt.Color(27, 42, 78));
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname2.setText("Intensity:");
        jPanel3.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 80, 30));

        add.setBackground(new java.awt.Color(243, 156, 18));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 50));

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 190, 50));

        firstname5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname5.setForeground(new java.awt.Color(27, 42, 78));
        firstname5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname5.setText("Plan Name:");
        jPanel3.add(firstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 30));

        firstname6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname6.setForeground(new java.awt.Color(27, 42, 78));
        firstname6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname6.setText("Goal:");
        jPanel3.add(firstname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 30));

        week_dura.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        week_dura.setForeground(new java.awt.Color(27, 42, 78));
        week_dura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Week", "2 Weeks", "3 Weeks", "4 Weeks" }));
        jPanel3.add(week_dura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        firstname7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname7.setForeground(new java.awt.Color(27, 42, 78));
        firstname7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname7.setText("Duration:");
        jPanel3.add(firstname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, -1, 30));

        Intensity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Intensity.setForeground(new java.awt.Color(27, 42, 78));
        Intensity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low. Medium", "High", "Extreme" }));
        jPanel3.add(Intensity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        firstname8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstname8.setForeground(new java.awt.Color(27, 42, 78));
        firstname8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname8.setText("Status:");
        jPanel3.add(firstname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 80, 30));

        m_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, 30));

        status.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        status.setForeground(new java.awt.Color(27, 42, 78));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Completed", "Paused" }));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));
        jPanel3.add(planId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, 30));

        Goal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Goal.setForeground(new java.awt.Color(27, 42, 78));
        Goal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lose 5kg", "Bulk Up", "Endurance", "Max Bench" }));
        Goal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoalActionPerformed(evt);
            }
        });
        jPanel3.add(Goal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        jPanel4.setBackground(new java.awt.Color(27, 42, 78));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WORKOUT PLAN FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 300, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        close.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("×");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        jPanel4.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 80, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerActionPerformed

    private void p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nameActionPerformed

    }//GEN-LAST:event_p_nameActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
  if(validateForm() != 1) return;


    String selectedMember = m_id.getSelectedItem().toString();
    String memberId = selectedMember.split(" ")[0]; 

    String planName = p_name.getSelectedItem().toString();
    String duration = week_dura.getSelectedItem().toString();
    String goal = Goal.getSelectedItem().toString();
    String intensity = Intensity.getSelectedItem().toString();
    String trainerName = Trainer.getText().trim();
    String currentStatus = status.getSelectedItem().toString();

    configclass dbc = new configclass();

    if(action.equals("Add")) {
        String sql = "INSERT INTO workout_plans (m_id, plan_name, duration, goal, intensity, trainer, status) "
                   + "VALUES ('" + memberId + "', '" + planName + "', '" + duration + "', '" 
                   + goal + "', '" + intensity + "', '" + trainerName + "', '" + currentStatus + "')";

        if(dbc.insertData(sql) == 1){
            JOptionPane.showMessageDialog(null, "Workout Plan Added Successfully!");
            close();
        }

    } else if(action.equals("Update")) {
      
        String sql = "UPDATE workout_plans SET "
                   + "m_id = '" + memberId + "', "
                   + "plan_name = '" + planName + "', "
                   + "duration = '" + duration + "', "
                   + "goal = '" + goal + "', "
                   + "intensity = '" + intensity + "', "
                   + "trainer = '" + trainerName + "', "
                   + "status = '" + currentStatus + "' "
                   + "WHERE wp_id = '" + planId.getText() + "'"; 

        dbc.updateData(sql);
        JOptionPane.showMessageDialog(null, "Updated Successfully!");
        close();
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit the application?",
            "Exit Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (response == javax.swing.JOptionPane.YES_OPTION) {

            close();
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void GoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workoutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Goal;
    public javax.swing.JComboBox<String> Intensity;
    public javax.swing.JTextField Trainer;
    public javax.swing.JPanel add;
    private javax.swing.JLabel close;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel firstname1;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname5;
    private javax.swing.JLabel firstname6;
    private javax.swing.JLabel firstname7;
    private javax.swing.JLabel firstname8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> m_id;
    public javax.swing.JComboBox<String> p_name;
    public javax.swing.JLabel planId;
    public javax.swing.JLabel st_label;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JComboBox<String> week_dura;
    // End of variables declaration//GEN-END:variables
}
